[build]
  publish = "."

  [build.environment]
    TWITCH_CLIENT_ID = "kc7d05tymbi6m6i1au75p9iv9ngfmr"
    TWITCH_CLIENT_SECRET = "5ob6aa0serpvdyhzoetia0w168xdp3"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    cache-control = "no-cache"
